# Generated by Django 4.2.1 on 2023-05-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_filma', models.CharField(max_length=100)),
                ('vrijeme_filma', models.IntegerField()),
                ('kapacitet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_sjedala', models.IntegerField()),
                ('projekcija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.projekcija')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
